# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "suruoxi"
repo_name: "HumanAIGC-arxiv-daily"
show_authors: True
show_links: True
show_badge: False
max_results: 20

publish_readme: True
publish_gitpage: True
publish_wechat: True

# file paths
black_list_path: 'blacklists.txt'
recent_trend_path: './pdf_analysis/recent_trends.txt'
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
claudeai_path: 'analysis_by_ai.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "1-World Model":
        filters: ["World model", "Generative World Model", "world simulation", "world reasoning" ]
    "2-VLA":
        filters: ["vision language model", "Embodied AI", "Embodied agents", "embodied robotics", "embodied reasoning", "iteractive embodied ai", "embodied learning"]
    "3-Video Generation":
        filters: ["Video Generation", "Video Synthesis", "Long Video Generation"]
